#!/bin/sh

INSTANCE="${1:-BAT0}"
ALERT_LOW="${2:-10}"

if test -e "/sys/class/power_supply/$INSTANCE"
then
    status=$(cat /sys/class/power_supply/$INSTANCE/status)
    capacity=$(cat /sys/class/power_supply/$INSTANCE/capacity)

    case "$status" in
        "Discharging")
            # symbol='↓'
            symbol=''
            ;;
        "Charging")
            symbol=''
            ;;
        "Full")
            # exit
            ;;
    esac

    if [ $capacity -lt 151 ]
      then icon=""
    fi
    if [ $capacity -lt 75 ]
      then icon=""
    fi
    if [ $capacity -lt 50 ]
      then icon=""
    fi
    if [ $capacity -lt 25 ]
      then icon=""
    fi
    if [ $capacity -lt 10 ]
      then icon=""
    fi

    # Full text
    echo "$icon $capacity% $symbol"

    # Short text
    echo "$icon $capacity% $symbol"

    # Color
    if test $capacity -le $ALERT_LOW -a $status = "Discharging"
    then
        echo "#FF0000"
    fi
fi
