#!/bin/sh
lock() {
    sleep .7 && i3lock -d -I 10 --color 475263
}

showMenu() {
        while [ "$select" != "NO" -a "$select" != "YES" ]; do
        select=$(echo -e 'NO\nYES' | dmenu -nb '#2f343f' -nf '#f3f4f5' -sb '#9575cd' -sf '#f3f4f5' -fn '-*-*-medium-r-normal-*-*-*-*-*-*-100-*-*' -i -p "Are you sure you want to $1?")
        [ -z "$select" ] && exit 0
        done
        [ "$select" = "NO" ] && exit 0
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        showMenu "logout"
        i3-msg exit
        ;;
    suspend)
        sudo systemctl suspend
        ;;
    hibernate)
        sudo systemctl hibernate
        ;;
    reboot)
        showMenu "reboot"
        sudo systemctl reboot
        ;;
    shutdown)
        showMenu "shutdown"
        sudo systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
